# Generated by Django 6.0.2 on 2026-02-17 05:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('COD', 'Cash on Delivery'), ('STRIPE', 'Stripe')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=30)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_signature', models.CharField(blank=True, default='', max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('failure_code', models.CharField(blank=True, default='', max_length=100)),
                ('failure_description', models.TextField(blank=True, default='')),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='idx_payments_order'), models.Index(fields=['user', '-created_at'], name='idx_payments_user_created'), models.Index(fields=['gateway_order_id'], name='idx_payments_gateway_order'), models.Index(fields=['gateway_payment_id'], name='idx_payments_gateway_payment'), models.Index(fields=['status'], name='idx_payments_status')],
            },
        ),
    ]
