# Generated by Django 6.0.2 on 2026-03-02 09:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.search import SearchVector
from django.db import migrations, models


def populate_search_vector(apps, schema_editor):
    """Populate search_vector for existing products."""
    Product = apps.get_model('products', 'Product')
    # Use raw SQL since SearchVector ORM requires the model's save()
    if Product.objects.exists():
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("""
                UPDATE products SET search_vector =
                    setweight(to_tsvector('english', COALESCE(name, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(short_description, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(description, '')), 'C') ||
                    setweight(to_tsvector('english', COALESCE(sku, '')), 'D')
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable pg_trgm extension for trigram similarity
        TrigramExtension(),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('query_normalized', models.CharField(db_index=True, max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'search_query_logs',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_products_search_gin'),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['-created_at'], name='idx_search_log_created'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['query_normalized', '-created_at'], name='idx_search_log_norm_date'),
        ),
        # Populate search_vector for existing products
        migrations.RunPython(populate_search_vector, migrations.RunPython.noop),
    ]
